{% set name = "databricks-sql-connector" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/databricks-sql-connector-{{ version }}.tar.gz
  sha256: 8085f53731ae85342583dc592ff19bf8aa84b5adde3a7951abb4a383238e594b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - future
    - thrift >=0.13.0

test:
  imports:
    - databricks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://databricks.com
  summary: Databricks SQL Connector for Python
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.databricks.com/dev-tools/python-sql-connector.html

extra:
  recipe-maintainers:
    - xylar
