{% set name = "databricks-sql-connector" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
    sha256: 4bc4654f8a51d6da5c1628660f4f0d6f04f0d047c82417943bf4c32fa1aedd98
  - url: https://github.com/databricks/databricks-sql-python/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 924c83d8a840f8747ccaf2c9678dea45fc736f92ee78c30276b0c9a8ec1f98dc
    folder: gh_src

build:
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.0.0
  run:
    - python
    - thrift >=0.16.0,<0.21.0
    - pandas >=1.2.5,<2.3.0  # [py<313]
    - pandas >=2.2.3,<2.3.0  # [py>=313]
    - lz4 >=4.0.2,<5.0.0
    - requests >=2.18.1,<3.0.0
    - oauthlib >=3.1.0,<4.0.0
    - openpyxl >=3.0.10,<4.0.0
    - urllib3 >=1.26
    - python-dateutil >=2.8.0,<3.0.0
  run_constrained:
    - pyarrow >=14.0.1  # [py<313]
    - pyarrow >=18.0.0  # [py>=313]

test:
  source_files:
    - gh_src/tests
  imports:
    - databricks
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - cd gh_src && pytest -vv tests/unit -k "not test_init_file_contents"
  requires:
    - pip
    - python
    - pytest >=7.1.2,<8.0.0
    - pyarrow

about:
  home: https://github.com/databricks/databricks-sql-python
  summary: Databricks SQL Connector for Python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://docs.databricks.com/dev-tools/python-sql-connector.html
  dev_url: https://github.com/databricks/databricks-sql-python
  description: |
    The Databricks SQL Connector for Python allows you to develop Python applications that connect to
    Databricks clusters and SQL warehouses. It is a Thrift-based client with no dependencies on ODBC 
    or JDBC. It conforms to the Python DB API 2.0 specification.

extra:
  recipe-maintainers:
    - xylar
