{% set name = "databricks-sql-connector" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/databricks-sql-connector-{{ version }}.tar.gz
  sha256: 0173eb74c15f8b7c7defd15c12e69bd7ad1dd11a29121744900661d93dc8ba81

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pandas >=1.3.0
    - pyarrow >=5.0.0
    - thrift >=0.13.0

test:
  imports:
    - databricks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://databricks.com
  summary: Databricks SQL Connector for Python
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.databricks.com/dev-tools/python-sql-connector.html

extra:
  recipe-maintainers:
    - xylar
