{% set name = "databricks-sql-connector" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/databricks-sql-connector-{{ version }}.tar.gz
  sha256: a3662374c65e7fea2ab20d1b33379078f7bf014e286a1b34d00706f4d1624e43

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7.1,<4.0.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7.1,<4.0.0
    - pandas >=1.3.0,<2.0.0
    - pyarrow >=9.0.0,<10.0.0
    - thrift >=0.13.0,<0.14.0

test:
  imports:
    - databricks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://databricks.com
  summary: Databricks SQL Connector for Python
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://docs.databricks.com/dev-tools/python-sql-connector.html

extra:
  recipe-maintainers:
    - xylar
